In [1]:
import numpy as np

## 1. DataTypes & Attributes

In [2]:
# NumPy's main datatype is ndarray
a1=np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2=np.array([[1,2,3.3],
           [4,5,6.5]])

a3=np.array([[[1,2,3],
             [4,5,6],
             [7,8,9]],
             [[10,11,12],
             [13,14,15],
              [16,17,18]]])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 3)

In [10]:
a1.ndim,a2.ndim,a3.ndim

(1, 2, 3)

In [11]:
a1.dtype,a2.dtype,a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [12]:
a1.size,a2.size,a3.size

(3, 6, 18)

In [13]:
type(a1),type(a2),type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [16]:
# Create a DataFrame from a NumPy array
import pandas as pd

df=pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating arrays

In [17]:
sample_array=np.array([1,2,3])
sample_array

array([1, 2, 3])

In [19]:
sample_array.dtype

dtype('int32')

In [20]:
ones=np.ones((2,3))

In [21]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
ones.dtype

dtype('float64')

In [23]:
type(ones)

numpy.ndarray

In [28]:
zeros=np.zeros((2,3))

In [30]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [31]:
range_array=np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [34]:
random_array=np.random.randint(0,10,size=(3,5))
random_array

array([[4, 8, 6, 8, 2],
       [5, 6, 4, 3, 0],
       [7, 4, 6, 0, 6]])

In [35]:
random_array.size

15

In [36]:
random_array.shape

(3, 5)

In [39]:
random_array_2=np.random.random((5,3))
random_array_2

array([[0.39555127, 0.0485563 , 0.5970539 ],
       [0.73860993, 0.64871466, 0.80353965],
       [0.65240059, 0.1909375 , 0.11302761],
       [0.74836964, 0.8909934 , 0.13873671],
       [0.3930467 , 0.57483576, 0.58580824]])

In [40]:
random_array_2.shape

(5, 3)

In [42]:
random_array_3=np.random.rand(5,3)
random_array_3

array([[0.85546615, 0.39743485, 0.04575856],
       [0.49802187, 0.89914758, 0.29157899],
       [0.7699938 , 0.66542198, 0.11386431],
       [0.07590615, 0.10892344, 0.03990213],
       [0.91595165, 0.5775417 , 0.17502956]])

In [ ]:
# Pseudo-random numbers
np.random.seed()